language: swift
osx_image: xcode10.1
sudo: required
branches:
  only:
    - master
env:
  global:
    - PROJECT="Semver.xcodeproj"
    - SCHEME="Semver"
    - IOS_SDK="iphonesimulator12.0"
    - MACOS_SDK="macosx10.14"
  matrix:
    - SDK="$IOS_SDK"      DESTINATION="platform=iOS Simulator,name=iPhone X,OS=12.0"
    - SDK="$MACOS_SDK"    DESTINATION="arch=x86_64"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

before_script:
  - swift package generate-xcodeproj

script:
  - swiftlint lint
  - xcodebuild clean build test
      -project "$PROJECT"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION"
      -configuration Debug
      -enableCodeCoverage YES
      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: "$FRAMEWORK.framework.zip"
  skip_cleanup: true
  on:
    repo: glwithu06/Semver.swift
    tags: true
